### ISSUE TITLE
replacemantToken allow empty string

### ISSUE THREAD

**Issue by zmarsel1** [nsarris/TranslitSharp#4]
https://github.com/nsarris/TranslitSharp/blob/77e2ec5682ff7d2cab1fad29083004309d5006ca/src/TranslitSharp/CharacterMap.cs#L10

is it necessary to check for empty string? what if i want to remove charachter whilte transliterating

**Comment by nsarris** [comment]
@zmarsel1 You are right, I will upload a patch for this.

**Comment by nsarris** [comment]
Resolved
